@startuml
class CommandManager {
    + CommandManager(model:Model)
    + Set(command:Command) : void
    + OnInput(point:Point) : bool
}
ICommand <|-- CommandManager
CommandManager o-> "currentCommand" Command
CommandManager --> "Model" Model
@enduml
